### ISSUE TITLE
Absorption feeling a little clunky

### ISSUE THREAD

**Issue by pagnabros** [Leafwing-Studios/fonts-of-power#100]
## What problem does the current design create?

I think that the part "The only time this does not occur is when you gain absorption at a time when it was not your turn, such as when it was received as a boon from an ally" is not worthy the possible confusion that could arise at the table because of it.

## What solution would you like?

I would personally remove that phrase but at the same I would make abilities that grant absorption granting more of it and make it disappear at the end of your next turn, not the start.

**Comment by alice-i-cecile** [comment]
We definitely need to simplify this. Unsure about the fix.

**Comment by alice-i-cecile** [comment]
Fixed in https://github.com/Leafwing-Studios/fonts-of-power/commit/b1681b91ca1459075592d5fc353ec42d9a025ba8 (oops, no PR because Git bit me...).

We can buff absorption granting powers as needed; the complexity isn't justified here.
