### ISSUE TITLE
The way attack of opportunities triggers (and the great number of reactions) can be problematic for solo monsters

### ISSUE THREAD

**Issue by pagnabros** [Leafwing-Studios/fonts-of-power#101]
## What problem does the current design create?

Action economy is already king in rpgs, and solo bosses already struggle a lot against parties of multiple characters because of it. I'm afraid the way reactions and attack of opportunities works atm could sour the problem even more, something I would like to avoid.

## What solution would you like?

Not sure yet about the best solution, but maybe attack of opportunities triggered by losing life could be removed, simply because it aggravate the action economy problem both for solo bosses but also for player characters when surrounded, which would be easily slaughtered causing a death spiral.

**Comment by alice-i-cecile** [comment]
Have you seen the "boss monsters get multiple turns per round" tech? I think that's the critical design idea that you're missing here.
