### ISSUE TITLE
Death's Door is too fussy and hard to balance

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/fonts-of-power#127]
## What problem does the current design create?

Death's Door creates tension, but pushes players towards simulationism and weird moral choices around executing downed foes (if you have foes that follow Death's Door).

It's also a fiddly mechanic that needs to be looked up every time it comes up, and is hard to balance.

## What solution would you like?

Remove Death's Door completely, and remove creatures who hit 0 HP from the fight. Use narrative mechanics (roll table??) to determine what happens when that occurs.

## What alternative(s) have you considered?

1. Simplify it. Again, doesn't solve most of the problems, and a simple solution is harder to balance.
2. Also remove Essence Tap.

## Additional context

#14 is a great example of the sort of headaches that you get here. The constant yo-yoing with healing from 5e was also problematic.

**Comment by pagnabros** [comment]
I think I could have a solution for the yo-yo healing, one that I already use in 5e but I don't know if it could traslate well for FoP

In dnd 5e only healing from actions can bring someone back up, healing from aura/passive/bonus actions can only stabilize a creature and back it up only if already stable

**Comment by alice-i-cecile** [comment]
We deliberately don't have healing skills, so that's not the problem here. My larger concerns are around the specialized rules required to make it balanceable, and the difficulties with player flow / memory.
