### ISSUE TITLE
The rows for the Features in the Character Sheet are too many and too small

### ISSUE THREAD

**Issue by Mibanfi** [Leafwing-Studios/fonts-of-power#137]
## What problem does the current design create?

Since the rows are so small, it is hard to write the full names and descriptions of the feats in legible handwriting and a lot of unused rows remain, which take up about a fourth of the sheet at higher levels and almost half at lower levels.

## What solution would you like?

Having less slots, but allocating more space to each of them.

## What alternative(s) have you considered?

Alternatively, Features could be written on separate cards like Actions.

**Comment by alice-i-cecile** [comment]
Closing out: the character sheets need a complete overhaul regardless.
