### ISSUE TITLE
Clean up sidebar items

### ISSUE THREAD

**Issue by plof27** [Leafwing-Studios/fonts-of-power#149]
Some categories/headings are missing from the sidebar on the left. We should ensure that all of these are present.

**Comment by alice-i-cecile** [comment]
@plof27 Classes are now added. Are there others that are missing?

**Comment by plof27** [comment]
Bladesworn is on the wrong header level, but otherwise I think we're good. Anything else missing can be grabbed on a final polish pass anyway.
