### ISSUE TITLE
Move subclass features back into same file as main class

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/fonts-of-power#89]
e.g. https://rules.fontsofpower.com/#/character-options/classes/paragon?id=causes

**Comment by alice-i-cecile** [comment]
Done now! Well, as soon as the open PRs are merged.

**Comment by bzm3r** [comment]
@alice-i-cecile Sweet, I was going to ask you what this entailed, as I didn't quite understand it. I'll look at the PRs.
