### ISSUE TITLE
Certain ailments are more powerful than others

### ISSUE THREAD

**Issue by pagnabros** [Leafwing-Studios/fonts-of-power#95]
## What problem does the current design create?

Is a balance-wise problem, mostly because there are affixes that let you choose any ailments and, as currently, you will always select the most powerful ones and never the others.

## What solution would you like?

Buffing or nerfing the ailments to make them more or less on the same level or classifying them into major or minor ailments and use the distiction to balance affixes/features that works for ailments.

## What alternative(s) have you considered?

Another solutions could be to avoid affixes/features that let you freely choose the ailment and instead making them fixed (with maybe some exception if you want versatility to be a thing of that particular affix/feature, but still avoid a completely free choice of all the ailments).

**Comment by alice-i-cecile** [comment]
These should definitely all be balanced. Which ones do you feel are weak? Which ones are too strong?

**Comment by pagnabros** [comment]
For example, unlucky feels much more weak than for example blinded or cursed. Also Defenseless and Taunted feels on the weaker spectrum of ailments, because they are more situational.

**Comment by alice-i-cecile** [comment]
From playtesting, Defenseless and Taunted were both *very* strong in the right situation :) Definitely agree that Unlucky might need some help. Perhaps it could also block crits?

https://github.com/Leafwing-Studios/fonts-of-power/blob/main/docs/src/rules/combat/conditions/ailments.md#unlucky

**Comment by alice-i-cecile** [comment]
@plof27 and I feel we should just cut unlucky.

**Comment by pagnabros** [comment]
I think the block crits would make it absolutely more tasty, but at the same time I think something more reliable instead of situational as a buff
