### ISSUE TITLE
Clarification on swapping arms and maximum gear point that can be equipped

### ISSUE THREAD

**Issue by pagnabros** [Leafwing-Studios/fonts-of-power#97]
As title, I'm a little confused if the current limit of 6 + 2 times your proficiency bonus is shared between all set of arms + armor.

**Comment by alice-i-cecile** [comment]
It should be shared between "currently equipped" sets.

**Comment by alice-i-cecile** [comment]
Reopening this, as we probably need to clarify this in the rules :)

**Comment by pagnabros** [comment]
Maybe polishinh + example could make things more clear?
