### ISSUE TITLE
Expertise feels not as impactful as the other stats

### ISSUE THREAD

**Issue by pagnabros** [Leafwing-Studios/fonts-of-power#98]
## What problem does the current design create?

I'm afraid Expertise could become the dump stat for min-maxers.

## What solution would you like?

A solution could be that the number of skills you have is 4+Expertise instead of a fixed 5, so that Expertise feels a little more rewarding.

**Comment by alice-i-cecile** [comment]
Interesting: expertise has felt *very* impactful in playtesting. Special attacks are very common, even for martial classes. Can you expand on your reasoning?

**Comment by pagnabros** [comment]
The perceived problem is that Expertise only influence the accuracy of your special attacks, while almost every other attributes has at least two or three imprortant stats that are influenced by it. Also, I coluld easily create a build that doesn't have any special attack, and dump Expertise to the ground because of it without other repercussions.

**Comment by alice-i-cecile** [comment]
Hmm. I don't mind the idea of scaling skills known with Expertise... I think a 1 to 1 ratio is too high, so maybe half Expertise?

**Comment by pagnabros** [comment]
I think is reasonable, honestly I'm not even sure is the best solution but I think Expertise should still influence at least two things
