### ISSUE TITLE
Afflictions stacking is tiresome to track 

### ISSUE THREAD

**Issue by pagnabros** [Leafwing-Studios/fonts-of-power#99]
## What problem does the current design create?

Afflictions, especially at low stacks, don't feel impactful enough to be worthy of the tracking required. 

## What solution would you like?

There are a lot of possible solutions, but one I think is the best is to make them have a fixed duration (1 minute or even the entire combat) unless removed to better differentiate them from ailments, and making them thatat 1 stack the deal 1d4 damage from the start, then 1d6 at 2 stacks, 1d8 at 3 and so on to a maximum of a d12 (or even d20 if you like the idea of aflictions becoming very dangerous).

**Comment by alice-i-cecile** [comment]
Affliction tracking was definitely annoying. 

1 minute durations don't make sense in this system; we should just do "end of combat' if we're moving in that direction.

**Comment by pagnabros** [comment]
making it "end of combat" is absolutely fine by me

**Comment by alice-i-cecile** [comment]
I think that a good solution here is to simply make them not tick down. This will require rebalance on how many are applied, but also how easy they are to remove.
